// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpyI6CwUPx2xKCDHNPMfRrOGGlQvVjT44',
    appId: '1:255084801688:android:3f42e003a0e8e5191c6aed',
    messagingSenderId: '255084801688',
    projectId: 'fbtt-acc3b',
    storageBucket: 'fbtt-acc3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8yqH7GDEBSLc1KQZgxBQKGvj2rXF_0o4',
    appId: '1:255084801688:ios:d8808db565c59b441c6aed',
    messagingSenderId: '255084801688',
    projectId: 'fbtt-acc3b',
    storageBucket: 'fbtt-acc3b.appspot.com',
    androidClientId: '255084801688-8ic5gg7e1r6d1c40p005la8gcgphqbjn.apps.googleusercontent.com',
    iosClientId: '255084801688-erajkdchammdq6m98lglda8v4ginsta8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbase',
  );

}